scanlist: ../test_scanlist.csv #data/scanlist.csv
test_data_path: data/test_data
seg_data_path: data/seg_data
output_data_path: data/output
segmap: configs/fastsurfer_atlas_map.csv
atlas_locs: [17,53,18,54] #17-Left_Hippocampus, 53-Right_Hippocampus, 18-Left_Amygdala , 54-Right_Amygdala
model: densenet3d121 # choices: cnn3d, resnet3d10, resnet3d18, densenet3d121
test_model: data/models/test_model.pth
benchmark_model: data/models/benchmark_model.pth #Optional for testing against
subgroup_axis: ['sex','age_group']
diagnosis_dict: {'hc': 0, 'ad': 1}
batch_size: 10